namespace FreeType.Bindings;

public enum FT_PaintFormat_
{
    FT_COLR_PAINTFORMAT_COLR_LAYERS = 1,
    FT_COLR_PAINTFORMAT_SOLID = 2,
    FT_COLR_PAINTFORMAT_LINEAR_GRADIENT = 4,
    FT_COLR_PAINTFORMAT_RADIAL_GRADIENT = 6,
    FT_COLR_PAINTFORMAT_SWEEP_GRADIENT = 8,
    FT_COLR_PAINTFORMAT_GLYPH = 10,
    FT_COLR_PAINTFORMAT_COLR_GLYPH = 11,
    FT_COLR_PAINTFORMAT_TRANSFORM = 12,
    FT_COLR_PAINTFORMAT_TRANSLATE = 14,
    FT_COLR_PAINTFORMAT_SCALE = 16,
    FT_COLR_PAINTFORMAT_ROTATE = 24,
    FT_COLR_PAINTFORMAT_SKEW = 28,
    FT_COLR_PAINTFORMAT_COMPOSITE = 32,
    FT_COLR_PAINT_FORMAT_MAX = 33,
    FT_COLR_PAINTFORMAT_UNSUPPORTED = 255,
}
