using ArgonUI.SourceGenerator;
using ArgonUI.UIElements;
using System;
using System.Collections.Generic;
using System.Text;

namespace ArgonUI.Styling;

/// <summary>
/// This class contains factory methods for all <see cref="UIElement"/>s in the ArgonUI assembly.
/// </summary>
/// <remarks>
/// The contents of this class are autogenerated by the <see cref="MergeStylesAttribute"/>.
/// </remarks>
[MergeStyles("ArgonUI")]
public static partial class ArgonUIStyles
{

}
