name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2022

    env:
      BuildProjects: "['ArgonUI/ArgonUI.csproj', 'ArgonUI.Backends.OpenGL/ArgonUI.Backends.OpenGL.csproj']"

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    #- name: Setup Windows 10 SDK
    #  uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.4
    - name: Restore dependencies
      shell: pwsh
      run: |
          foreach($proj in (ConvertFrom-JSON "${{env.BuildProjects}}")) {
            dotnet restore ${{ github.workspace }}/$proj
          }
    - name: Build
      shell: pwsh
      run: |
          foreach($proj in (ConvertFrom-JSON "${{env.BuildProjects}}")) {
            msbuild ${{ github.workspace }}/$proj -t:rebuild -property:Configuration=Release
          }
